# Generated by Django 5.1.3 on 2025-01-02 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
