# Generated by Django 5.1.3 on 2025-01-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_applicant_applied_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
