# Generated by Django 5.1.3 on 2025-01-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='role',
        ),
    ]
